stages:
  - build

job1:
  stage: build
  tags:
    - macos
  script:
    - xcodebuild build -workspace OrgChartGen.xcworkspace -scheme OrgChartGen -configuration Distribution SYMROOT=$(pwd)/build | xcpretty && exit ${PIPESTATUS[0]}
  artifacts:
    paths:
      - build/Release/OrgChartGen.app